#!/bin/bash

IM2TXT_DIR=/public/jthurst3/MemeCaptcha

# Path to checkpoint file or a directory containing checkpoint files. Passing
# a directory will only work if there is also a file named 'checkpoint' which
# lists the available checkpoints in the directory. It will not work if you
# point to a directory with just a copy of a model checkpoint: in that case,
# you will need to pass the checkpoint path explicitly.
CHECKPOINT_PATH="${IM2TXT_DIR}/models/char_im2txt/train"

# Vocabulary file generated by the preprocessing script.
VOCAB_FILE="${IM2TXT_DIR}/character_input_data/word_counts_min1.txt"

# JPEG image file to caption.
IMAGE_FILE="${IM2TXT_DIR}/val_images/*.jpg"

echo $CHECKPOINT_PATH
echo "hello there"

# Build the inference binary.
module load bazel
bazel build -c opt im2txt/run_inference

# Ignore GPU devices (only necessary if your GPU is currently memory
# constrained, for example, by running the training script).
#export CUDA_VISIBLE_DEVICES=""

# Run inference to generate captions.
bazel-bin/im2txt/run_inference \
  --checkpoint_path=${CHECKPOINT_PATH} \
  --vocab_file=${VOCAB_FILE} \
  --input_files=${IMAGE_FILE} \
  --max_caption_length="80" \
